name: CI-CD

on:
  push:
    branches: [ "master" ]

jobs:

  pull_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout main
        uses: actions/checkout@master
   
      - name: deploy to my vps
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd mjolnir-front
            docker compose down
            git pull origin main
            docker compose build
            docker compose up -d
            
